// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DQUnC0lJKdnNxQx443JupF_XCELRjxI',
    appId: '1:793053963173:web:be618ebb4448ff6d94be4c',
    messagingSenderId: '793053963173',
    projectId: 'flutter-project-a6ccc',
    authDomain: 'flutter-project-a6ccc.firebaseapp.com',
    storageBucket: 'flutter-project-a6ccc.appspot.com',
    measurementId: 'G-X0Q7S2ZF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJjbvZ7nhN_omX7BDHVaKn_7xjblNEtEU',
    appId: '1:793053963173:android:eee38ad44deb499094be4c',
    messagingSenderId: '793053963173',
    projectId: 'flutter-project-a6ccc',
    storageBucket: 'flutter-project-a6ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb5JfSXY5_p3fwMoyYJwh0nNTWGIjJ9vQ',
    appId: '1:793053963173:ios:992b0d8ffe5c456994be4c',
    messagingSenderId: '793053963173',
    projectId: 'flutter-project-a6ccc',
    storageBucket: 'flutter-project-a6ccc.appspot.com',
    iosClientId: '793053963173-5ivchb7m0dru9egeq86d3lroljgmbqvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb5JfSXY5_p3fwMoyYJwh0nNTWGIjJ9vQ',
    appId: '1:793053963173:ios:992b0d8ffe5c456994be4c',
    messagingSenderId: '793053963173',
    projectId: 'flutter-project-a6ccc',
    storageBucket: 'flutter-project-a6ccc.appspot.com',
    iosClientId: '793053963173-5ivchb7m0dru9egeq86d3lroljgmbqvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
